version: "3"

services:
  netascore:
    image: plusmobilitylab/netascore:latest
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./data:/usr/src/netascore/data
    - ./resources:/usr/src/netascore/resources
    - ./sql:/usr/src/netascore/sql
    - ./core:/usr/src/netascore/core 

    command: "examples/settings_osm_query.yml"
    depends_on:
      netascore-db:
        condition: service_healthy

  netascore-db:
    image: postgis/postgis:13-3.2
    ports:
    - "5434:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 20s
      retries: 120